filter_opt:
  fc: 600.0
  fh: 800
  fs: 2200.0
  ftype: Band pass
  gain: 1
  iirftype: Butterworth
  order: 1.0
  win: Black man
freq_opt:
  apply_ifft: true
  apply_win: true
  file: ../data/aaah.wav
  linear: true
  log: false
  rm_freqs: 0.0
  seg_m: 8192.0
  seg_n: 8192.0
  win: hanning
glob_opt:
  exec: FIR filter design
