filter_opt:
  fc: 600.0
  fh: 800.0
  fs: 2200.0
  ftype: Band reject
  gain: 10.0
  iirftype: Butterworth
  order: 60.0
  win: Hamming
freq_opt:
  apply_ifft: true
  apply_win: true
  file: ../data/aaah.wav
  linear: true
  log: false
  rm_freqs: 0
  seg_m: 178
  seg_n: 44100
  win: hamming
glob_opt:
  exec: FIR filter design
