filter_opt:
  fc: 800.0
  fh: 1200.0
  fs: 44100.0
  ftype: Low pass
  gain: 20.0
  iirftype: Butterworth
  order: 20.0
  win: Hamming
freq_opt:
  apply_ifft: true
  apply_win: true
  file: /home/aalonso/workspace/pds/sigbox-0.0.1/data/aaah.wav
  linear: false
  log: false
  rm_freqs: 0.0
  seg_m: 0
  seg_n: 35927
  win: hamming
glob_opt:
  exec: FIR filter design
