filter_opt:
  fc: 1500.0
  fh: 2500.0
  fs: 8000.0
  ftype: Band reject
  gain: 25.0
  iirftype: Butterworth
  order: 30.0
  win: Hamming
freq_opt:
  apply_ifft: true
  apply_win: true
  file: /home/aalonso/workspace/pds/sigbox-0.0.1/data/aaah_8000.wav
  linear: false
  log: false
  rm_freqs: 0.0
  seg_m: 2324
  seg_n: 2643
  win: hamming
glob_opt:
  exec: FIR filter design
